name: update_data

on:
  schedule:
    - cron: '0 */2 * * *' # Execute 2 hours 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install necesary libraries
        run: bash apt-get install -y curl libssl-dev libcurl4-openssl-dev libxml2-dev
      
      - name: Install R
        uses: r-lib/actions/setup-r@v2 # Instalo R
        with: 
          r-version: '4.1.1'
        
      - name: Run Data Extraction
        run: Rscript src/data_extraction.R
      
      - name: Push data to Github
        run: bash src/github.sh
