name: make_predictions

on:
  schedule:
    - cron: '0 10 * * *'  
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Update
        run: sudo apt-get update
        
      - name: Install necesary libraries
        run:  sudo apt-get install -y curl libssl-dev libcurl4-openssl-dev libxml2-dev
      
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with: 
          r-version: '4.1.1'
        
      - name: Run Retrain Check
        run: Rscript src/get_predictions.R
      
      - name: Push data to Github
        run: bash src/github.sh
