name: retrain_model

on:
  repository_dispatch:
    types: retrain_model

jobs:
  build:
    runs-on: ubuntu-18.04 
    container: 
     image: asachet/rocker-tidymodels
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install R
        uses: r-lib/actions/setup-r@v2 # Instalo R
        with: 
          r-version: '4.1.1'
      
      - name: Create and populate .Renviron file
        run: |
          echo TOKEN="$secrets.TOKEN" >> ~/.Renviron
          echo api_key="$secrets.API_KEY" >> ~/.Renviron
      
      - name: Setup Neptune
        run: Rscript src/neptune_setup.R
        
      - name: Retrain Model
        run: Rscript src/model_train.R
      
      - name: Push data to Github
        run: bash src/github.sh
